# GitHub Actions workflow: Build and push Docker image to GHCR and optionally Docker Hub
# Pre-requisites:
# - Optional: repository secrets DOCKERHUB_USERNAME, DOCKERHUB_TOKEN for Docker Hub publishing
# - GITHUB_TOKEN is provided by GitHub and used for GHCR

name: Docker Publish

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - ".github/workflows/docker-publish.yml"
      - "**/*.py"
      - "TampermonkeyScript/**"
      - "modules/**"
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - "Dockerfile"
      - "**/*.py"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (GHCR)
        id: meta_ghcr
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          flavor: latest=true

      - name: Extract metadata (Docker Hub)
        if: ${{ env.DOCKERHUB_USERNAME != '' }}
        id: meta_dh
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          flavor: latest=true

      - name: Login to GHCR
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: ${{ (env.DOCKERHUB_USERNAME != '' ) && (env.DOCKERHUB_TOKEN != '' ) && ( startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta_ghcr.outputs.tags }}
          labels: ${{ steps.meta_ghcr.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (Docker Hub)
        if: ${{ (env.DOCKERHUB_USERNAME != '' ) && (env.DOCKERHUB_TOKEN != '') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta_dh.outputs.tags }}
          labels: ${{ steps.meta_dh.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
